# -*- coding: utf-8 -*-
"""YouTube Channel Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hp_4JwU-SQPsCuq5TWd0fhDsEiFhELSB
"""

from google.colab import files
uploaded= files.upload()

import pandas as pd
import io
import plotly.express as px

df = pd.read_csv(io.BytesIO(uploaded['most_subscribed_youtube_channels.csv']))
display(df)

#cleaning dataset
#removing commas between numbers
df=df.replace(',', '',regex=True)
display(df)

#histogram
fig= px.histogram(df, x='subscribers', title='Subscribers of Most Subscribed Youtube Channels')
fig.show()

#piechart
figpie = px.pie(df, values='subscribers', names='category', title='YouTube Categories')
figpie.show()

figbox = px.box(df, y='started', title='Years Started')
figbox.show()